-- Active: 1723632330684@@127.0.0.1@5433@record
CREATE TABLE IF NOT EXISTS url(
    uuid integer generated by default as identity primary key,
    id character VARYING UNIQUE NOT NULL,
    url character VARYING UNIQUE NOT NULL
);