// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package urlsnipper

import (
	"context"
	"sync"
)

// Ensure, that urlStorageMock does implement urlStorage.
// If this is not the case, regenerate this file with moq.
var _ urlStorage = &urlStorageMock{}

// urlStorageMock is a mock implementation of urlStorage.
//
//	func TestSomethingThatUsesurlStorage(t *testing.T) {
//
//		// make and configure a mocked urlStorage
//		mockedurlStorage := &urlStorageMock{
//			GetURLFunc: func(ctx context.Context, id string) (string, error) {
//				panic("mock out the GetURL method")
//			},
//			SetURLFunc: func(ctx context.Context, id string, url string) error {
//				panic("mock out the SetURL method")
//			},
//		}
//
//		// use mockedurlStorage in code that requires urlStorage
//		// and then make assertions.
//
//	}
type urlStorageMock struct {
	// GetURLFunc mocks the GetURL method.
	GetURLFunc func(ctx context.Context, id string) (string, error)

	// SetURLFunc mocks the SetURL method.
	SetURLFunc func(ctx context.Context, id string, url string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetURL holds details about calls to the GetURL method.
		GetURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// SetURL holds details about calls to the SetURL method.
		SetURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// URL is the url argument value.
			URL string
		}
	}
	lockGetURL sync.RWMutex
	lockSetURL sync.RWMutex
}

// GetURL calls GetURLFunc.
func (mock *urlStorageMock) GetURL(ctx context.Context, id string) (string, error) {
	if mock.GetURLFunc == nil {
		panic("urlStorageMock.GetURLFunc: method is nil but urlStorage.GetURL was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetURL.Lock()
	mock.calls.GetURL = append(mock.calls.GetURL, callInfo)
	mock.lockGetURL.Unlock()
	return mock.GetURLFunc(ctx, id)
}

// GetURLCalls gets all the calls that were made to GetURL.
// Check the length with:
//
//	len(mockedurlStorage.GetURLCalls())
func (mock *urlStorageMock) GetURLCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetURL.RLock()
	calls = mock.calls.GetURL
	mock.lockGetURL.RUnlock()
	return calls
}

// SetURL calls SetURLFunc.
func (mock *urlStorageMock) SetURL(ctx context.Context, id string, url string) error {
	if mock.SetURLFunc == nil {
		panic("urlStorageMock.SetURLFunc: method is nil but urlStorage.SetURL was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
		URL string
	}{
		Ctx: ctx,
		ID:  id,
		URL: url,
	}
	mock.lockSetURL.Lock()
	mock.calls.SetURL = append(mock.calls.SetURL, callInfo)
	mock.lockSetURL.Unlock()
	return mock.SetURLFunc(ctx, id, url)
}

// SetURLCalls gets all the calls that were made to SetURL.
// Check the length with:
//
//	len(mockedurlStorage.SetURLCalls())
func (mock *urlStorageMock) SetURLCalls() []struct {
	Ctx context.Context
	ID  string
	URL string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
		URL string
	}
	mock.lockSetURL.RLock()
	calls = mock.calls.SetURL
	mock.lockSetURL.RUnlock()
	return calls
}
